// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.1
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace github.events
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.11.1")]
	public partial class Comment : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"Comment\",\"namespace\":\"github.events\",\"fields\":[{\"name\":\"" +
				"author\",\"type\":\"string\"},{\"name\":\"body\",\"type\":\"string\"},{\"name\":\"time\",\"type\":{" +
				"\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}}]}");
		private string _author;
		private string _body;
		private System.DateTime _time;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return Comment._SCHEMA;
			}
		}
		public string author
		{
			get
			{
				return this._author;
			}
			set
			{
				this._author = value;
			}
		}
		public string body
		{
			get
			{
				return this._body;
			}
			set
			{
				this._body = value;
			}
		}
		public System.DateTime time
		{
			get
			{
				return this._time;
			}
			set
			{
				this._time = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.author;
			case 1: return this.body;
			case 2: return this.time;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.author = (System.String)fieldValue; break;
			case 1: this.body = (System.String)fieldValue; break;
			case 2: this.time = (System.DateTime)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
