// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.1
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace github.events
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	/// <summary>
	/// Represents the state of a Pull Request.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.11.1")]
	public partial class PullRequest : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""PullRequest"",""doc"":""Represents the state of a Pull Request."",""namespace"":""github.events"",""fields"":[{""name"":""id"",""type"":""long""},{""name"":""url"",""type"":""string""},{""name"":""title"",""type"":""string""},{""name"":""author"",""type"":""string""},{""name"":""opened_on"",""type"":{""type"":""long"",""logicalType"":""timestamp-millis""}},{""name"":""closed_on"",""default"":null,""type"":[""null"",{""type"":""long"",""logicalType"":""timestamp-millis""}]},{""name"":""status"",""default"":null,""type"":[""null"",{""type"":""enum"",""name"":""Status"",""namespace"":""github.events"",""symbols"":[""OPEN"",""APPROVED"",""CLOSED""]}]},{""name"":""comments"",""default"":[],""type"":{""type"":""array"",""items"":{""type"":""record"",""name"":""Comment"",""namespace"":""github.events"",""fields"":[{""name"":""author"",""type"":""string""},{""name"":""body"",""type"":""string""},{""name"":""time"",""type"":{""type"":""long"",""logicalType"":""timestamp-millis""}}]}}}]}");
		private long _id;
		private string _url;
		private string _title;
		private string _author;
		private System.DateTime _opened_on;
		private System.Nullable<System.DateTime> _closed_on;
		private System.Nullable<github.events.Status> _status;
		private IList<github.events.Comment> _comments;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return PullRequest._SCHEMA;
			}
		}
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		public string url
		{
			get
			{
				return this._url;
			}
			set
			{
				this._url = value;
			}
		}
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				this._title = value;
			}
		}
		public string author
		{
			get
			{
				return this._author;
			}
			set
			{
				this._author = value;
			}
		}
		public System.DateTime opened_on
		{
			get
			{
				return this._opened_on;
			}
			set
			{
				this._opened_on = value;
			}
		}
		public System.Nullable<System.DateTime> closed_on
		{
			get
			{
				return this._closed_on;
			}
			set
			{
				this._closed_on = value;
			}
		}
		public System.Nullable<github.events.Status> status
		{
			get
			{
				return this._status;
			}
			set
			{
				this._status = value;
			}
		}
		public IList<github.events.Comment> comments
		{
			get
			{
				return this._comments;
			}
			set
			{
				this._comments = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.id;
			case 1: return this.url;
			case 2: return this.title;
			case 3: return this.author;
			case 4: return this.opened_on;
			case 5: return this.closed_on;
			case 6: return this.status;
			case 7: return this.comments;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.id = (System.Int64)fieldValue; break;
			case 1: this.url = (System.String)fieldValue; break;
			case 2: this.title = (System.String)fieldValue; break;
			case 3: this.author = (System.String)fieldValue; break;
			case 4: this.opened_on = (System.DateTime)fieldValue; break;
			case 5: this.closed_on = (System.Nullable<System.DateTime>)fieldValue; break;
			case 6: this.status = fieldValue == null ? (System.Nullable<github.events.Status>)null : (github.events.Status)fieldValue; break;
			case 7: this.comments = (IList<github.events.Comment>)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
