// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.1
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Events
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	/// <summary>
	/// The event of a pull request being opened.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.11.1")]
	public partial class PullRequestOpened : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""PullRequestOpened"",""doc"":""The event of a pull request being opened."",""namespace"":""Events"",""fields"":[{""name"":""id"",""type"":""long""},{""name"":""url"",""type"":""string""},{""name"":""title"",""type"":""string""},{""name"":""author"",""type"":""string""},{""name"":""opened_on"",""type"":""string""}]}");
		private long _id;
		private string _url;
		private string _title;
		private string _author;
		private string _opened_on;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return PullRequestOpened._SCHEMA;
			}
		}
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		public string url
		{
			get
			{
				return this._url;
			}
			set
			{
				this._url = value;
			}
		}
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				this._title = value;
			}
		}
		public string author
		{
			get
			{
				return this._author;
			}
			set
			{
				this._author = value;
			}
		}
		public string opened_on
		{
			get
			{
				return this._opened_on;
			}
			set
			{
				this._opened_on = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.id;
			case 1: return this.url;
			case 2: return this.title;
			case 3: return this.author;
			case 4: return this.opened_on;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.id = (System.Int64)fieldValue; break;
			case 1: this.url = (System.String)fieldValue; break;
			case 2: this.title = (System.String)fieldValue; break;
			case 3: this.author = (System.String)fieldValue; break;
			case 4: this.opened_on = (System.String)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
